### ISSUE TITLE
Part 4: Storing Data into Postgre database

### ISSUE THREAD

**Issue by amberkar** [amberkar/Final_Project#4]
- [ ] create a database table for Ann Arbor events within 20 miles

- [ ] create a database table for Denver events within 20 miles

- [ ] create a database that looks at price and sorts event from lowest to highest price

**Comment by aerenchyma** [comment]
These database table plans reflect a possible misunderstanding of how databases/database tables should be used. You should think about what entities you need to complete the project -- e.g. one entity may be Events, another may be Places.

Events might have fields like
- Reference to a row in the Place table
- Price

etc., to leverage the possibilities a relational database allows you to have. For an example, you can consider how Project 6 changed the CSV data into database tables!

The sorting you describe here would be ideal to do in Python programming -- but you may also want to consider what queries you will make to the database (you could do a query with an ORDER BY to sort by price, as well).
